# Site settings
exclude: [".gitignore", "README.md", "Gemfile"]
title: "Claude Shannon"
email: "oe@itsoc.org"
description: ""
url: "https://chmbrlnd.github.io/"
# url: "http://shannon.tamu.edu"
baseurl: "shannon/" # GitHub
# twitter_username: ""
# github_username: ""
# Build settings
markdown: kramdown
