# Site settings
exclude: [".gitignore", "README.md", "Gemfile"]
title: "A Few Bits of Information Theory"
email: "oe@itsoc.org"
description: ""
#url: "https://chmbrlnd.github.io/"
url: "http://shannon.tamu.edu"
baseurl: "" # GitHub
# twitter_username: ""
# github_username: ""
# Build settings
markdown: kramdown
