# Site settings
exclude: [".gitignore", "README.md", "Gemfile"]
title: "Claude Shannon"
email: "chmbrlnd@tamu.edu"
description: ""
url: "https://chmbrlnd.github.io/shannon"
baseurl: "" # GitHub
# twitter_username: ""
# github_username: ""
# Build settings
markdown: kramdown
